# Artificial Neural Network


# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Importing the dataset

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x=data.iloc[:,3:-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
y=data.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# Encoding categorical data

In [5]:
#label encording the gender column

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()


In [7]:
x[:,2]=le.fit_transform(x[:,2])

In [8]:
print(x[:,2])

[0 0 0 ... 0 1 0]


In [9]:
#onehot encording the geography column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')

In [12]:
x=np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# Splliting the dataset into training and test sets

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [15]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [16]:
x_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 0, 141533.19],
       [0.0, 1.0, 0.0, ..., 1, 1, 11276.48],
       [0.0, 1.0, 0.0, ..., 1, 0, 192950.6]], dtype=object)

In [17]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

# Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc=StandardScaler()

In [20]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [21]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [22]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Initializing the ANN

In [23]:
ann=tf.keras.models.Sequential()

In [24]:
#adding the input layer and first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [26]:
#adding the second hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [28]:
#adding the output layer

In [29]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN

In [30]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#prepare a neural network model for training

In [31]:
#optimizer=update the weights of neural network durimg training
#adam=optimizer algorithm
#loss fn=how well the model is performing
#metrics=measure the performance of the model

In [32]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7259
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.8009
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4390 - accuracy: 0.8075
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4285 - accuracy: 0.8148
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4224 - accuracy: 0.8194
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4176 - accuracy: 0.8221
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4125 - accuracy: 0.8254
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4055 - accuracy: 0.8307
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3951 - accuracy: 0.8350
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3832 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3331 - accuracy: 0.8625
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 0.8634
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3324 - accuracy: 0.8648
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 0.8643
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3324 - accuracy: 0.8636
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3323 - accuracy: 0.8645
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3323 - accuracy: 


# Predicting the result of a single observation¶

In [33]:
#Use our ANN model to predict if the customer with the following informations will leave the bank:

#Geography: France

#Credit Score: 600

#Gender: Male

#Age: 40 years old

#Tenure: 3 years

#Balance: $ 60000

#Number of Products: 2

#Does this customer have a credit card? Yes

#Is this customer an Active Member: Yes

#Estimated Salary: $ 50000

#So, should we say goodbye to that customer?

In [34]:
    print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 153ms/step
[[0.03045641]]


In [35]:
    print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 34ms/step
[[False]]


In [36]:
ypred=ann.predict(x_test)
ypred

63/63 [==============================] - 0s 2ms/step


array([[0.31156868],
       [0.23569082],
       [0.15669437],
       ...,
       [0.11474133],
       [0.20513327],
       [0.23433217]], dtype=float32)

In [37]:
ypred=(ypred>0.5)
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [38]:
print(np.concatenate((ypred.reshape(len(ypred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [40]:
cm=confusion_matrix(y_test,ypred)
cm

array([[1520,   75],
       [ 206,  199]], dtype=int64)

In [41]:
accuracy_score(y_test,ypred)

0.8595